version: "3.4"

services:
  minio:
    image: minio/minio:RELEASE.2021-09-15T04-54-25Z
    entrypoint: sh
    # Create an empty dir, which translates into an empty bucket
    command: -c 'mkdir -p /data/blobvault && /usr/bin/docker-entrypoint.sh server /data --console-address ":9001"'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - 9000:9000 # main port
      - 9001:9001 # web console port
