version: "3.4"

services:
  postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-pwd111}
      POSTGRES_DB: ${DB_NAME:-database}
    ports:
      - ${DB_PORT:-5432}:5432

  api:
    depends_on:
      - postgres

  worker:
    depends_on:
      - postgres
